version: "3"
services:
    app:
        build: .
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www/html/
        networks:
            - public
            - internal
    db:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: db_name
            MYSQL_USER: db_user
            MYSQL_PASSWORD: db_password
            MYSQL_ROOT_PASSWORD: db_password
        volumes:
            - db_stripstrap:/var/lib/mysql/
        networks:
            - internal

volumes:
    db_stripstrap:

networks:
    public:
        driver: bridge
    internal:
        driver: bridge
        internal: true