#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homepage

sign_in:
    path: /signin
    controller: App\Controller\UserController::userForm
logout:
    path: /logout

# ADMIN PANEL BELOW
admin_home:
    path: /admin
    controller: App\Controller\AdminController::home

admin_game:
    path: /admin/game/{edit}
    controller: App\Controller\AdminController::gameForm

admin_game_list:
    path: /admin/game/list
    controller: App\Controller\AdminController::gameList

admin_picture:
    path: /admin/game/list/{document}
    controller: App\Controller\DefaultController::downloadDocument

#admin_gamelist_edit:
#    path:     /admin/game/list
#    controller: App\Controller\AdminController::editGame

#admin_gamelist_delete:
 #   path:     /admin/game/list/{delete} 
 #   controller: App\Controller\AdminController::deleteGame
