#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homepage

sign_in:
    path: /signin
    controller: App\Controller\UserController::userForm
logout:
    path: /logout

# ADMIN PANEL BELOW
admin_home:
    path: /admin
    controller: App\Controller\AdminController::home
