#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homepage

profileCard:
    path: /profileCard
    controller: App\Controller\DefaultController::profileCard