#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homepage

# ADMIN PANEL BELOW
admin_home:
    path: /admin
    controller: App\Controller\AdminController::userList

admin_user_detail:
    path: /admin/user/details/{user}
    controller: App\Controller\AdminController::userDetails