#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /
    controller: App\Controller\DefaultController::homepage

sign_in:
    path: /signin
    controller: App\Controller\UserController::userForm
    
logout:
    path: /logout

login:
    path:   /login
    controller: App\Controller\DefaultController::login

# ADMIN PANEL BELOW
admin_home:
    path: /admin
    controller: App\Controller\AdminController::home

download_document:
    path: /document/{document}
    controller: App\Controller\DefaultController::downloadDocument
